# INFO: Generate machine key using command below.
# nix run nixpkgs#ssh-to-age -- ssh-to-age < /etc/ssh/ssh_host_ed25519_key.pub
keys:
  - &user_ssh age1c0yqrgs2gahffngks7qdtt9mqgfx9mz6ytcx66equh2hqmz90qxqt4eqrc
  - &laptop_ssh age1q5v4fl45505gkt7qav8kh2t9g33d4me464wfw3aywa20shvj9pxsclgpg8
creation_rules:
  - path_regex: hosts/laptop/secrets/[^/]+\.(yaml)$
    key_groups:
      - age:
          - *user_ssh
          - *laptop_ssh
