user:
    password:
        hashed: ENC[AES256_GCM,data:VpaJ+e8Q3LpeeQX0hEk0Hdaz/Syx+VZalAjSl4k7RVk5ntifRicwU+JorNwjPBDVYPHmRL/3wUpAq43039e0WnETBQMX6fXYoA==,iv:dQYcwZZzIIl0cZUl4Z4WxaL/LuZ+buqRUpYhln40O+U=,tag:uJbu7Kow6AOaMonChPqUog==,type:str]
    keys:
        sops:
            public: ENC[AES256_GCM,data:/YKO5UWx7Y0TXVg7fopuR5Z4y0McR/HbBpe191Q7fV5QY8CEcrke5w5bHTocthu0uaPwABdxTOnYrQk+wkg=,iv:nStd7kkPiK2qqLL2M9SStUCTAoacLSZSZziYPFBwl1Q=,tag:1+V+FmmsFe5NM+J8Bk84oA==,type:str]
            private: ENC[AES256_GCM,data:ZpYfC1gw0NaTZMZWhjWN1FwZ2Fou67if0mssqM7Txq+DDUCuzvNjwVFkBNxo47k/07JCwW2S2AJTCgohf6VhoD1Y5Mrq2AZ5uDg=,iv:IAKJalpuHTeMAhNFiq7cJMrYyIb3rvnmG3HGWYsjHHM=,tag:2jCI6ysmyyIpN4O1ig2IjA==,type:str]
        ssh:
            public: ENC[AES256_GCM,data:vO6kTXYKQsBa9zcNeZ/J3ZtP3vYnv/jjzjM3cqOlE31kUBQsLGry8wEaJViR/jWL2K/q9NdjIjCxiunV7ZfeBopAzctAdvwtL1R5aYFmeDA=,iv:t50xG8WEl+KnwBoMkHgqFyaBdDZuWvLkABqiqKk5KF8=,tag:WDZ/kU8ko+jjdVWPK6TY0Q==,type:str]
            private: ENC[AES256_GCM,data:oGzxXGFnkzqlNukaex0PYyMfhjUmgmas8fsAZEBlgShF/o1OxyHLqDq5BCmmib0qF0L1jHSL4q5xkSGrO5V8HdRSvznLele5EVS/kpxNb94Kl6gJGrVLiym5xl1xDaGRwXzQYFNwDX1Ic89qWsiuYgIoCCbUfuh5H0Vvzl3hb32SQpB+hg8h/mRvGirgq3RdJ2z9pRPmxpou8vQhQsiWmdG6B6xjzbS6zqBeXQwcNBdxQIQF3kSzhhYlfwgvrRxSfBxHRQbIe6MKfMW220/omvPvMVEtZjJL2NBKkoMUyL77fq/0AZQ0MNSufR8dlAxt/FR7OFEK12g7B4866wvExeIjjgRJq5GCl19sfBel9g0nCSRFRsKlNrr3PzragRdfPERd6ZE9aFX8Rdp1AFP2h1ZL7Jg5yFbLDbFwafQZRRxq94w0KU2rYlUF2SJdWs31wZfyLEPx1JgyGuHRDuX0UnBkjG59zFrHl5rXmkUIyNeM4c3zqQFbG36qQQx2TDdh5d/bvIA0sM8IJFdTKCOB,iv:3J749SYLqhg+EncA0sTbZXMsyE2H8QncPJNMC8MQzIE=,tag:CqJi9XsBAEolaYbYCSTFpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c0yqrgs2gahffngks7qdtt9mqgfx9mz6ytcx66equh2hqmz90qxqt4eqrc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUkxaUm1qbGQxa2pQc3JU
            cDFzOGs5Sk1MQTRGUmdLZDgxbmdZNkhUWkZRCk1ONkIvRVBxQmZrZElwMnhGNkdU
            c3M2TXZDUGFEaC9SMWtQODNncHlMbFEKLS0tIC84UXFUTHVDdUZjTjRsM3pvcjhk
            KzFjZitDTEZGZVkvaWZzYlZNWmQzRlUKXbecVCkIHwHX5sFDZW4MgnMH2cSvPAxD
            jGT67rAr61pdA0p5fR/CUMdsygvRqzhp/TwutRmIbV6aaZaZEaLSKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q5v4fl45505gkt7qav8kh2t9g33d4me464wfw3aywa20shvj9pxsclgpg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6elI4cVZSNWdTTFdLYzBi
            dCtyQ1hYUkRpWVZPQ3o1Um9HeUgwREdWRkVvCmk5VStnNDlxckhwWDZHZUFmQlo2
            V0hnRlBxdXlGNHl0ZGMxNFBnaVhPVzAKLS0tIDc5Z3B0M1AzSUpsUnFnbFdZN2lG
            WmJEUml1cmlRQ0xCdWllWGVEeElXU1UKMSvrhqwoOrpdJuAtC4Y31PUrcVmb1sPK
            FJXeTgvdNBXrzzazJbAwJ4gzSSRX4qFjtiZqBxaJrDhNJapO13/ouQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-08T21:15:06Z"
    mac: ENC[AES256_GCM,data:AE4H1TdCVajr6aL5p9emmKL/f7NtfcZGFsqtCQyM3ryMrPnhU7A6oacvQr1BZlSkWGsiKOzNZRHDov/9NGaudbXh5bx58QtEH/foqCH90Jr6S+PFNmYC17XC8tNt2q/6PV+muMBpXG2TC3cvbjZHZNL87ZUwcvEDlCCJ75fsLeg=,iv:Ls2g+0a8muAC5TKabgcFraY50MxAzPGD6xk57eUz560=,tag:6kFubeqYwx5p84kuZmBIoQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
